spring: #???? ??
  profiles:
    active: local
  datasource: #???? 2?
    url: jdbc:mysql://localhost:3306/jpaBoard?serverTimezone=Asia/Seoul #4?
    username: root
    password: Dldytpq!23
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: #???? 2?
    hibernate: #???? 4?
      ddl-auto: create #???? 6?
      properties: #???? 4?
        hibernate: #???? 6?
          # show_sql: true #???? 8?
          format_sql: true #???? 8?
          use_sql_comments: true

  logging:
    level: #???? ??
      org.hibernate.SQL: debug #???? 2?
      # org.hibernate.type: trace #???? 2?
